---
- name: Update web servers
  hosts: all
  become: true

  tasks:
    - name: Ensure nginx is at the latest version
      ansible.builtin.apt:
        name: nginx
        state: latest

    - name: Run a shell command to update apt cache
      ansible.builtin.shell: "git clone https://github.com/RakshaShekhar07/Amazon-Clone.git"

    - name: Copy web content to /var/www/html
      ansible.builtin.synchronize:
        src: ./Amazon-Clone/*    # The directory where your files are located locally
        dest: /var/www/html    # The target directory on the remote server
        owner: root           # Set ownership to root
        group: root           # Set group to root
        mode: '0644'          # Set permissions to -rw-r--r-- (owner can read/write, group and others can read)
        recurse: yes          # Recursively copy all files and directories inside /srv/myfiles/
