---
- name: Update web servers
  hosts: all
  become: true

  tasks:
    - name: Ensure nginx is at the latest version
      ansible.builtin.apt:
        name: nginx
        state: latest

    - name: Clone the Git repository to the remote server (force)
      ansible.builtin.git:
        repo: 'https://github.com/RakshaShekhar07/Amazon-Clone.git'
        dest: /var/www/html/Amazon-Clone  # Directory on the remote server
        clone: yes
        update: yes  # Update the repo if already cloned
        force: yes   # Force the clone operation, even if directory exists

    - name: Copy web content to /var/www/html
      ansible.builtin.copy:
        src: /var/www/html/Amazon-Clone/*  # The directory on the remote server
        dest: /var/www/html                # The target directory on the remote server
        owner: root
        group: root
        mode: '0644'
        recurse: yes
